name:                void-service-manager
version:             0.1.0.0
github:              "githubuser/void-service-manager"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/waynevanson/void-service-manager#readme>

dependencies:
- base
- filepath
- directory
- text
- transformers
- unix
- validation

library:
  source-dirs: src

executables:
  void-service-manager:
    main:                Main.hs
    source-dirs:         bin
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - void-service-manager

tests:
  void-service-manager-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - void-service-manager
